### ISSUE TITLE
Cannot open Settings

### ISSUE THREAD

**Issue by nikhita** [CellarD0-0r/whatever#12]
When I click on my account icon on the bottom left and then select Settings, nothing happens. I also noticed that no action occurs for other options as well, like `Help and Learning`.

Also just wanted to say that Whatever is great and thanks for making it! :smile:

**Comment by CellarD0-0r** [comment]
At first, thank you, @nikhita ! :)
Did you download installer from sourceforge / release here, or build it from master? In the second case there could be some problems, cause the latest version on master is not stable (my fault, yes).

**Comment by nikhita** [comment]
I downloaded the installer from the release on github.

**Comment by CellarD0-0r** [comment]
Hmm, that's strange. What OS do you use?

**Comment by nikhita** [comment]
Sorry for the late reply.

from `cat /etc/os-release`:
I'm on Ubuntu 14.04.4 LTS (Trusty Tahr).

Linux kernel version from `uname -a`:
4.2.0-34-generic

**Comment by CellarD0-0r** [comment]
@nikhita try to update your ubuntu. I used whatever under 16.04, 16.10 and now under 17.04, and there was no problem with settings.

**Comment by nikhita** [comment]
Cool, closing this issue then.
