### ISSUE TITLE
Clicking links inside Evernote results in error message

### ISSUE THREAD

**Issue by stormgrass** [CellarD0-0r/whatever#2]
When clicking any link in any note within Whatever, a pop-up opens with an error message. Screenshot:

![selection_001](https://cloud.githubusercontent.com/assets/16881520/23016854/5b0a4a86-f438-11e6-87ca-2d2c4edb03f1.png)

Ubuntu 16.04, Whatever latest install from Sourceforge.

**Comment by CellarD0-0r** [comment]
@stormgrass It's strange, but I don't have this error: links open correctly (windows 10). I'll try it a bit later on Ubuntu.

 Did you try to sign in once more to open link, as it's told in the error message?

**Comment by stormgrass** [comment]
@CellarD0-0r Hi, thanks for your quick reply. I actually did, and it simply opens up the whole webapp inside that one window again. Clicking another link results in the same thing happening all over again.

**Comment by stormgrass** [comment]
@CellarD0-0r something I forgot to mention and just realized now: the window title for the error message says: "Evernote error: access denied".

**Comment by CellarD0-0r** [comment]
@stormgrass I got what you're talking about. Caught this error too. Maybe opening external links in the default browser will fix this.

**Comment by CellarD0-0r** [comment]
p.s. Monkey testing rocks! :)

**Comment by stormgrass** [comment]
:) Yeah, opening links in external default browser would be great!

**Comment by antoan** [comment]
I get the same issue on Ubuntu 14.04 64bit, installed from Sourceforge.

**Comment by benjsnellings** [comment]
this still does not work for me on ubuntu 17. I open into a splash screen and thus cannot access pages

**Comment by x35a** [comment]
still doesn't work, os: Deepin 15.5, default browser: Chrome 66
