### ISSUE TITLE
Problem opening links in notes

### ISSUE THREAD

**Issue by zalloy** [CellarD0-0r/whatever#20]
Hi there,

I'm really enjoying using Whatever with Evernote. It's wonderful compared to the other Evernote clients that are available for Linux. Just one small issue...I noticed that when I add links to a note, and then I try to open them, I get an "Access Denied" error message implying that I need to log into Evernote when I'm already logged in. 

I checked this against the behavior when running Evernote Web in Chrome, and when I click a link there, it opens a new tab with a message that I'm now leaving Evernote and confirming that I want to open the link.

Is it possible to have the same functionality in Whatever that we have on Evernote Web for opening links? 

Thanks,
Laurie

**Comment by CellarD0-0r** [comment]
See issue #2
