### ISSUE TITLE
Error during click link inside note

### ISSUE THREAD

**Issue by abdonmosqueira** [CellarD0-0r/whatever#26]
Hi,

When clicking in any link saved in notes, open new windows with the follow message:

"Oops, we encountered an error.

Access denied.
You have accessed a location on this server that is not available.
You may need to Sign in to your account to access this page."

The work around is copy the link and paste in the browser.

Regards.

**Comment by sbrshk** [comment]
Hi, 
please, check issue #2

**Comment by abdonmosqueira** [comment]
Thanks @CellarD0-0r.
