### ISSUE TITLE
Compile Instructions

### ISSUE THREAD

**Issue by NicoHood** [CellarD0-0r/whatever#3]
Hi,
I try to compile whatever for ArchLinux which I want to put in AUR. However there is not description about how to compile and which dependencies are required. Could you please add this information?

**Comment by CellarD0-0r** [comment]
Hello, @NicoHood 
Frankly speaking, I have no experience in packaging for Arch, but, probably, found the salvation for your problem. 

For some reason electron-builder cannot package a pkg.tar.xz, but I found a script, whilch converts .deb packages into Arch Linux packages: [<b>debtap</b> by helixarch](https://github.com/helixarch/debtap). 

Hope it could help. Tell me, if not, so I'll try to package it manually.

**Comment by CellarD0-0r** [comment]
P.S. no dependencies :)

**Comment by NicoHood** [comment]
Converting a debian package is the most aweful way I can think of. Especially because of static libraries.
Arch already provides an electron package, so electron should not be shipped again within the package. Also because of security reasons.

Can you please give me some details on how you compile the program? Or is it just packaging, as its only webpages (I never packages electron apps, but I know they are mostly webpages). We really need to avoid static dependencies.

**Comment by CellarD0-0r** [comment]
Yeah, there is packaging in its simple way, cause it is just a wrapper for the web version (but I'm working on making it 'not-only-one-more-electron-wrapper'). So I package it with electron-builder. Maybe it can be easier for you to re-package it from the source code using electron-builder or electron-packager.

Also I know that there are some variations of electron-builder for different platforms and distributions (e.q. for windows and linux red hat, if I'm not mistaken).  Or maybe building an AppImage with standard electron-builder will be a salvation?

**Comment by CellarD0-0r** [comment]
@NicoHood
I think this issue could be closed
