### ISSUE TITLE
Clicking on url throws an error

### ISSUE THREAD

**Issue by fsdias** [CellarD0-0r/whatever#4]
Steps to reproduce: While signed in to an Evernote account, create a note and add an url to it. Then double click on it and this error will appear

Oops, we encountered an error.

Access denied.
You have accessed a location on this server that is not available.
You may need to Sign in to your account to access this page.

**Comment by CellarD0-0r** [comment]
@fsdias thank you for report.
Please, check issue #2

**Comment by fsdias** [comment]
sorry for the duplicate, somehow I missed it even though it has two tags
