### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by rudrab** [CellarD0-0r/whatever#7]
Hi,

I am an icon maker for linux. You can check my icons at https://github.com/rudrab/Shadow.
The problem is I can't recreate the "W" of your icon good enough. if it is a font, can you kindly give me the font name? or an svg of the icon or just the W without any background and highlight, please?

**Comment by CellarD0-0r** [comment]
Hey, 

The font is [Annabelle](http://allfont.ru/download/annabelle/), background colors: #228B22 (forest green) and #008B8B (dark cyan). Good luck and thank you :)

**Comment by rudrab** [comment]
Hi, 
Thanks a lot.
https://github.com/rudrab/Shadow/blob/master/scalable/apps/whatever.svg is how the icon looks in my theme. Hope, you will like it.

**Comment by CellarD0-0r** [comment]
Thanks :)
